"""Add GSC performance metrics to monitoring table

Revision ID: 0918c8f8946d
Revises: 2025_03_25_add_invoice
Create Date: 2025-05-24 10:44:19.332848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0918c8f8946d'
down_revision: Union[str, None] = '2025_03_25_add_invoice'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gsc_accounts_project_id_fkey', 'gsc_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'gsc_accounts', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('keywords_project_id_fkey', 'keywords', type_='foreignkey')
    op.create_foreign_key(None, 'keywords', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('projects_user_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='auth', ondelete='CASCADE')
    op.drop_constraint('wordpress_credentials_project_id_fkey', 'wordpress_credentials', type_='foreignkey')
    op.create_foreign_key(None, 'wordpress_credentials', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    
    # Add GSC performance metric columns to monitoring_project_stats table
    op.add_column('monitoring_project_stats', sa.Column('gsc_clicks', sa.Integer(), nullable=True, server_default='0'), schema='public')
    op.add_column('monitoring_project_stats', sa.Column('gsc_impressions', sa.Integer(), nullable=True, server_default='0'), schema='public')
    op.add_column('monitoring_project_stats', sa.Column('gsc_ctr', sa.Float(), nullable=True, server_default='0.0'), schema='public')
    op.add_column('monitoring_project_stats', sa.Column('gsc_position', sa.Float(), nullable=True, server_default='0.0'), schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove GSC performance metric columns
    op.drop_column('monitoring_project_stats', 'gsc_position', schema='public')
    op.drop_column('monitoring_project_stats', 'gsc_ctr', schema='public')
    op.drop_column('monitoring_project_stats', 'gsc_impressions', schema='public')
    op.drop_column('monitoring_project_stats', 'gsc_clicks', schema='public')
    
    op.drop_constraint(None, 'wordpress_credentials', schema='public', type_='foreignkey')
    op.create_foreign_key('wordpress_credentials_project_id_fkey', 'wordpress_credentials', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'projects', schema='public', type_='foreignkey')
    op.create_foreign_key('projects_user_id_fkey', 'projects', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_constraint(None, 'keywords', schema='public', type_='foreignkey')
    op.create_foreign_key('keywords_project_id_fkey', 'keywords', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'gsc_accounts', schema='public', type_='foreignkey')
    op.create_foreign_key('gsc_accounts_project_id_fkey', 'gsc_accounts', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
