"""fix gsc account foreign key schema

Revision ID: 277d825e19ef
Revises: ca7fa8c4da45
Create Date: 2025-02-05 14:56:49.427451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277d825e19ef'
down_revision: Union[str, None] = 'ca7fa8c4da45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('keywords_project_id_fkey', 'keywords', type_='foreignkey')
    op.create_foreign_key(None, 'keywords', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('projects_user_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='auth', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', schema='public', type_='foreignkey')
    op.create_foreign_key('projects_user_id_fkey', 'projects', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_constraint(None, 'keywords', schema='public', type_='foreignkey')
    op.create_foreign_key('keywords_project_id_fkey', 'keywords', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
