"""Add new fields to Keywords model

Revision ID: 4cd28526a7d6
Revises: aad0a216e5b1
Create Date: 2025-02-03 18:28:57.293344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd28526a7d6'
down_revision: Union[str, None] = 'aad0a216e5b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('keywords', sa.Column('search_volume', sa.Integer(), nullable=True))
    op.add_column('keywords', sa.Column('difficulty', sa.Integer(), nullable=True))
    op.add_column('keywords', sa.Column('intent', sa.String(), nullable=True))
    op.add_column('keywords', sa.Column('cpc', sa.Float(), nullable=True))
    op.add_column('keywords', sa.Column('competition', sa.Float(), nullable=True))

    # Update existing rows with default values
    op.execute("UPDATE keywords SET search_volume = 0, difficulty = 0, intent = 'Unknown', cpc = 0.0, competition = 0.0")

    # Now make the columns non-nullable
    op.alter_column('keywords', 'search_volume', nullable=False)
    op.alter_column('keywords', 'difficulty', nullable=False)
    op.alter_column('keywords', 'intent', nullable=False)
    op.alter_column('keywords', 'cpc', nullable=False)
    op.alter_column('keywords', 'competition', nullable=False)

    # Handle foreign key changes
    op.drop_constraint('keywords_project_id_fkey', 'keywords', type_='foreignkey')
    op.create_foreign_key(None, 'keywords', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('projects_user_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='auth', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', schema='public', type_='foreignkey')
    op.create_foreign_key('projects_user_id_fkey', 'projects', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_constraint(None, 'keywords', schema='public', type_='foreignkey')
    op.create_foreign_key('keywords_project_id_fkey', 'keywords', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('keywords', 'competition')
    op.drop_column('keywords', 'cpc')
    op.drop_column('keywords', 'intent')
    op.drop_column('keywords', 'difficulty')
    op.drop_column('keywords', 'search_volume')
    # ### end Alembic commands ###
