"""add is_active column to project table

Revision ID: 54c3599bb868
Revises: 3a37fa941306
Create Date: 2025-02-20 18:43:30.441637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c3599bb868'
down_revision: Union[str, None] = '3a37fa941306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gsc_accounts_project_id_fkey', 'gsc_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'gsc_accounts', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('keywords_project_id_fkey', 'keywords', type_='foreignkey')
    op.create_foreign_key(None, 'keywords', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    
    # Add is_active column as nullable first
    op.add_column('projects', sa.Column('is_active', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE projects SET is_active = true")
    # Make the column non-nullable
    op.alter_column('projects', 'is_active', nullable=False)
    
    op.drop_constraint('projects_user_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='auth', ondelete='CASCADE')
    op.drop_constraint('wordpress_credentials_project_id_fkey', 'wordpress_credentials', type_='foreignkey')
    op.create_foreign_key(None, 'wordpress_credentials', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wordpress_credentials', schema='public', type_='foreignkey')
    op.create_foreign_key('wordpress_credentials_project_id_fkey', 'wordpress_credentials', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'projects', schema='public', type_='foreignkey')
    op.create_foreign_key('projects_user_id_fkey', 'projects', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_column('projects', 'is_active')
    op.drop_constraint(None, 'keywords', schema='public', type_='foreignkey')
    op.create_foreign_key('keywords_project_id_fkey', 'keywords', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'gsc_accounts', schema='public', type_='foreignkey')
    op.create_foreign_key('gsc_accounts_project_id_fkey', 'gsc_accounts', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
