"""Added the keywords model

Revision ID: aad0a216e5b1
Revises: add_business_type_to_projects
Create Date: 2025-01-22 11:49:06.487046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aad0a216e5b1'
down_revision: Union[str, None] = 'add_business_type_to_projects'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['public.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_keywords_created_at', 'keywords', ['created_at'], unique=False, schema='public')
    op.create_index('idx_keywords_name', 'keywords', ['name'], unique=False, schema='public')
    op.create_index('idx_keywords_project_id', 'keywords', ['project_id'], unique=False, schema='public')
    op.alter_column('projects', 'industries',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('projects', 'services',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.drop_constraint('projects_user_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='auth', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', schema='public', type_='foreignkey')
    op.create_foreign_key('projects_user_id_fkey', 'projects', 'users', ['user_id'], ['id'], referent_schema='auth', onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('projects', 'services',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('projects', 'industries',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.drop_index('idx_keywords_project_id', table_name='keywords', schema='public')
    op.drop_index('idx_keywords_name', table_name='keywords', schema='public')
    op.drop_index('idx_keywords_created_at', table_name='keywords', schema='public')
    op.drop_table('keywords', schema='public')
    # ### end Alembic commands ###
