"""add_featured_image_style_to_projects

Revision ID: add_featured_image_style
Revises: add_brand_tone_settings
Create Date: 2025-01-16 19:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'add_featured_image_style'
down_revision: Union[str, None] = 'add_brand_tone_settings'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('featured_image_style', sa.String(), nullable=True), schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'featured_image_style', schema='public')
    # ### end Alembic commands ###
