"""add_brand_tone_settings_to_projects

Revision ID: add_brand_tone_settings
Revises: 429f9a7850f1
Create Date: 2025-01-16 18:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'add_brand_tone_settings'
down_revision: Union[str, None] = '429f9a7850f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('brand_tone_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'brand_tone_settings', schema='public')
    # ### end Alembic commands ### 