"""fix gsc account project relationship

Revision ID: ca7fa8c4da45
Revises: 5c5758730298
Create Date: 2025-02-05 14:54:28.130280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca7fa8c4da45'
down_revision: Union[str, None] = '5c5758730298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('keywords', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'in'::character varying"))
    op.drop_constraint('keywords_project_id_fkey', 'keywords', type_='foreignkey')
    op.create_foreign_key(None, 'keywords', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('projects_user_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='auth', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', schema='public', type_='foreignkey')
    op.create_foreign_key('projects_user_id_fkey', 'projects', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_constraint(None, 'keywords', schema='public', type_='foreignkey')
    op.create_foreign_key('keywords_project_id_fkey', 'keywords', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('keywords', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'in'::character varying"))
    # ### end Alembic commands ###
