"""Add new fields to Keywords model

Revision ID: e09c21d40e93
Revises: 4cd28526a7d6
Create Date: 2025-02-04 15:37:13.719901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e09c21d40e93'
down_revision: Union[str, None] = '4cd28526a7d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add country column as nullable first
    op.add_column('keywords', sa.Column('country', sa.String(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE keywords SET country = 'in' WHERE country IS NULL")
    
    # Make the column non-nullable
    op.alter_column('keywords', 'country',
                    nullable=False,
                    server_default=sa.text("'in'"))
    
    op.drop_constraint('keywords_project_id_fkey', 'keywords', type_='foreignkey')
    op.create_foreign_key('keywords_project_id_fkey', 'keywords', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('projects_user_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key('projects_user_id_fkey', 'projects', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='auth', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_user_id_fkey', 'projects', schema='public', type_='foreignkey')
    op.create_foreign_key('projects_user_id_fkey', 'projects', 'users', ['user_id'], ['id'], referent_schema='auth')
    op.drop_constraint('keywords_project_id_fkey', 'keywords', schema='public', type_='foreignkey')
    op.create_foreign_key('keywords_project_id_fkey', 'keywords', 'projects', ['project_id'], ['id'])
    
    # First remove the server default
    op.alter_column('keywords', 'country', server_default=None)
    
    # Then drop the column
    op.drop_column('keywords', 'country')
    # ### end Alembic commands ###
