"""Add Razorpay payment table

Revision ID: f41ed12e9289
Revises: d33a407cf4ff
Create Date: 2025-03-21 13:37:15.202852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f41ed12e9289'
down_revision: Union[str, None] = 'd33a407cf4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('razorpay_payments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('project_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('razorpay_order_id', sa.String(), nullable=True),
        sa.Column('razorpay_payment_id', sa.String(), nullable=True),
        sa.Column('razorpay_signature', sa.String(), nullable=True),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.Column('currency', sa.String(), nullable=False, server_default='INR'),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['public.projects.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
    )
    
    op.drop_constraint('gsc_accounts_project_id_fkey', 'gsc_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'gsc_accounts', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('keywords_project_id_fkey', 'keywords', type_='foreignkey')
    op.create_foreign_key(None, 'keywords', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('projects_user_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='auth', ondelete='CASCADE')
    op.drop_constraint('wordpress_credentials_project_id_fkey', 'wordpress_credentials', type_='foreignkey')
    op.create_foreign_key(None, 'wordpress_credentials', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('razorpay_payments', schema='public')
    
    op.drop_constraint(None, 'wordpress_credentials', schema='public', type_='foreignkey')
    op.create_foreign_key('wordpress_credentials_project_id_fkey', 'wordpress_credentials', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'projects', schema='public', type_='foreignkey')
    op.create_foreign_key('projects_user_id_fkey', 'projects', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_constraint(None, 'keywords', schema='public', type_='foreignkey')
    op.create_foreign_key('keywords_project_id_fkey', 'keywords', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'gsc_accounts', schema='public', type_='foreignkey')
    op.create_foreign_key('gsc_accounts_project_id_fkey', 'gsc_accounts', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
